# Generated by Django 5.0.4 on 2026-02-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellingt_price',
            new_name='selling_price',
        ),
    ]
